#@p and @r are variables.
#@p = The Player.
#@r = The Reward Amount.
usevault: true
reward: 'say @p got @r'
#Message to tell player when they recieve their reward.
#@mk = Mob Kills.
message: 'You won @r for killing @mk valid mobs!'
#Reward per mob.
rate: 0.1
#Valid Mobs (Mobs that count for your reward when killed)
mobs:
  - Zombie
  - Chicken
  - Creeper
placerewards:
  mobmassacre.extra:
    1: 80
    2: 50
    3: 20
  anotherpermission.node:
    1: 10
    2: 20
    3: 30
activeworlds:
  - world
  - world_nether