main: cat.gay.spherret.plugins.MobMassacre.Start
name: MobMassacre
version: 1.0
author: Spherret.
description: MobMassacre.
commands:
  score:
  restartonnext:
  restartnow:
  top:
permissions:
  mobmassacre.seeothers:
    default: true
  mobmassacre.restart:
    default: op